name: chillphim_ios
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  file_picker: ^8.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  camera: ^0.12.0+1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"

flutter_native_splash:
  color: "#0F0F13"
  image: assets/images/icon_app.png
  color_dark: "#0F0F13"
  image_dark: assets/images/icon_app.png
  android_12:
    color: "#0F0F13"
    image: assets/images/icon_app.png
    color_dark: "#0F0F13"
    image_dark: assets/images/icon_app.png
  ios: true
  web: false
  fullscreen: false

flutter:
  uses-material-design: true
